 "use client";
import Link from "next/link";
import Image from "next/image";
import { Minus, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { useCart } from "@/components/cart-provider";

export default function CartPage(){
 const {items,remove,updateQty,subtotal,couponCode,couponDiscount,couponMessage,applyCoupon,clearCoupon}=useCart(); const [coupon,setCoupon]=useState(couponCode);
 return <main className="container-z py-10"><h1 className="serif text-4xl">Your Cart</h1>{!items.length?<div className="py-20 text-center"><p className="text-muted">Your cart is empty.</p><Link href="/shop" className="inline-block mt-5 bg-black text-white px-6 py-3 text-xs tracking-[.15em]">SHOP SHIRTS</Link></div>:<div className="grid lg:grid-cols-[1fr_360px] gap-10 mt-8">
 <div className="space-y-5">{items.map(i=><div key={i.key} className="flex gap-4 border-b hairline pb-5"><div className="relative w-24 h-30 bg-[#f7f6f2]"><Image src={i.product.images[0]} alt={i.product.name} fill className="object-cover"/></div><div className="flex-1"><Link href={`/products/${i.product.slug}`} className="font-medium text-sm">{i.product.name}</Link><p className="text-xs text-muted mt-1">Size: {i.size} · {i.color}</p><p className="font-semibold mt-2">₹{((i.product.sale_price??i.product.price)*i.quantity).toLocaleString("en-IN")}</p><div className="flex items-center gap-3 mt-3"><div className="border flex"><button className="p-2" onClick={()=>updateQty(i.key,i.quantity-1)}><Minus size={13}/></button><span className="px-3 py-2 text-xs">{i.quantity}</span><button className="p-2" onClick={()=>updateQty(i.key,i.quantity+1)}><Plus size={13}/></button></div><button onClick={()=>remove(i.key)} className="text-xs text-muted flex gap-1 items-center"><Trash2 size={13}/> Remove</button></div></div></div>)}</div>
 <aside className="border hairline p-6 h-fit"><h2 className="font-semibold">Order Summary</h2><div className="flex justify-between mt-6 text-sm"><span>Subtotal</span><span>₹{subtotal.toLocaleString("en-IN")}</span></div><div className="flex justify-between mt-3 text-sm"><span>Shipping</span><b>FREE</b></div><div className="mt-5"><div className="flex gap-2"><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Coupon code" className="border hairline px-3 py-3 text-sm flex-1"/><button onClick={()=>applyCoupon(coupon)} className="border px-4 text-xs">APPLY</button></div>{couponMessage&&<p className="text-xs text-muted mt-2">{couponMessage} {couponCode&&<button onClick={clearCoupon} className="underline ml-2">Remove</button>}</p>}</div><div className="border-t hairline mt-5 pt-5 flex justify-between"><span>Discount</span><span>-₹{couponDiscount.toLocaleString("en-IN")}</span></div><div className="flex justify-between mt-3"><b>Total</b><b>₹{Math.max(0,subtotal-couponDiscount).toLocaleString("en-IN")}</b></div><Link href="/checkout" className="block text-center bg-black text-white py-4 mt-6 text-xs font-bold tracking-[.15em]">CHECKOUT</Link><Link href="/shop" className="block text-center mt-4 text-xs underline">Continue Shopping</Link></aside>
 </div>}</main>
}
