'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { Heart, Minus, Plus, ShoppingBag, Zap } from 'lucide-react';
import { Product } from '@/lib/types';
import { useCart } from './cart-provider';

export function ProductDetail({product}:{product:Product}){
 const {add}=useCart();const [image,setImage]=useState(product.images[0]);const [size,setSize]=useState(product.sizes[1]||product.sizes[0]||'M');const [color,setColor]=useState(product.colors[0]||'');const [qty,setQty]=useState(1);const [pincode,setPincode]=useState('');const [checked,setChecked]=useState(false);
 const price=product.sale_price??product.price; const discount=product.sale_price?Math.round((1-product.sale_price/product.price)*100):0;
 function addCart(){add(product,size,color,qty)}
 function buy(){add(product,size,color,qty);window.location.href='/checkout'}
 return <div className="grid lg:grid-cols-[1.05fr_.95fr] gap-8 lg:gap-14"><div className="grid grid-cols-5 gap-2"><div className="col-span-1 space-y-2">{product.images.map((src,i)=><button key={src+i} onClick={()=>setImage(src)} className={`relative aspect-[4/5] bg-[#f6f5f1] w-full ${image===src?'ring-2 ring-black':''}`}><Image src={src} alt={`${product.name} view ${i+1}`} fill className="object-cover"/></button>)}</div><div className="col-span-4 relative aspect-[4/5] bg-[#f6f5f1]"><Image src={image} alt={product.name} fill priority className="object-cover"/></div></div>
 <div><div className="flex gap-2 items-center">{product.badge&&<span className="text-[10px] bg-[var(--yellow)] px-2 py-1 tracking-wider">{product.badge}</span>}{discount>0&&<span className="text-[10px] border px-2 py-1">-{discount}%</span>}</div><h1 className="serif text-4xl md:text-5xl mt-4 leading-tight">{product.name}</h1><div className="flex items-center gap-3 mt-4 text-sm"><span>★★★★★</span><span className="text-muted">No reviews yet</span></div><div className="mt-5 flex items-center gap-3"><span className="text-2xl font-semibold">₹{price.toLocaleString('en-IN')}</span>{product.sale_price&&<span className="text-muted line-through">₹{product.price.toLocaleString('en-IN')}</span>}</div><p className="text-muted text-sm leading-6 mt-5">{product.description}</p>
 <div className="mt-7"><div className="flex justify-between text-sm"><b>Size</b><button className="underline text-muted">Size chart</button></div><div className="flex gap-2 mt-3 flex-wrap">{product.sizes.map(s=><button key={s} onClick={()=>setSize(s)} className={`min-w-12 px-4 py-3 border text-sm ${size===s?'bg-black text-white':''}`}>{s}</button>)}</div></div>
 <div className="mt-6"><b className="text-sm">Color</b><div className="flex gap-2 mt-3 flex-wrap">{product.colors.map(c=><button key={c} onClick={()=>setColor(c)} className={`px-4 py-3 border text-sm ${color===c?'bg-black text-white':''}`}>{c}</button>)}</div></div>
 <div className="grid grid-cols-3 gap-3 mt-7 text-xs"><div><span className="text-muted block">Fit</span>{product.fit}</div><div><span className="text-muted block">Fabric</span>{product.fabric}</div><div><span className="text-muted block">Pattern</span>{product.pattern}</div></div>
 <div className="flex items-center gap-3 mt-7"><div className="border flex"><button className="p-3" onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={14}/></button><span className="px-4 py-3 text-sm">{qty}</span><button className="p-3" onClick={()=>setQty(Math.min(product.stock,qty+1))}><Plus size={14}/></button></div><span className="text-xs text-muted">{product.stock>0?`${product.stock} available`:'Out of stock'}</span></div>
 <div className="grid grid-cols-2 gap-2 mt-5"><button disabled={!product.stock} onClick={addCart} className="border border-black py-4 text-xs font-bold tracking-[.12em] flex justify-center items-center gap-2 disabled:opacity-40"><ShoppingBag size={16}/> ADD TO CART</button><button disabled={!product.stock} onClick={buy} className="bg-black text-white py-4 text-xs font-bold tracking-[.12em] flex justify-center items-center gap-2 disabled:opacity-40"><Zap size={16}/> BUY NOW</button></div><button className="w-full border hairline py-4 mt-2 text-xs flex justify-center gap-2"><Heart size={16}/> ADD TO WISHLIST</button>
 <div className="border-t hairline mt-8 pt-6"><b className="text-sm">Delivery</b><div className="flex gap-2 mt-3"><input value={pincode} onChange={e=>setPincode(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="Enter pincode" className="border hairline px-4 py-3 text-sm flex-1"/><button onClick={()=>setChecked(true)} className="border px-5 text-xs">CHECK</button></div>{checked&&<p className="text-xs text-muted mt-3">India-wide delivery · FREE SHIPPING ACROSS INDIA. Delivery estimate is configured by the store.</p>}</div>
 <div className="border-t hairline mt-7 pt-6 space-y-5 text-sm"><details open><summary className="font-medium cursor-pointer">Product details</summary><p className="text-muted leading-6 mt-3">SKU: {product.sku}<br/>Premium men's shirt designed for modern everyday styling.</p></details><details><summary className="font-medium cursor-pointer">Care instructions</summary><p className="text-muted leading-6 mt-3">Follow the care label supplied with the final product. Do not publish care claims until the actual garment care instructions are confirmed.</p></details></div></div></div>
}
